//src9
const actionTypes = Object.freeze({
  PROCESS_LOGOUT: 'PROCESS_LOGOUT',

  //app
  APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
  SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

  //user, 41ms31ss
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
});

export default actionTypes;
