const actionTypes = Object.freeze({
  PROCESS_LOGOUT: 'PROCESS_LOGOUT',

  //app
  APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
  SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
  CHANGE_LANGUAE: 'CHANGE_LANGUAE',

  //user,
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  ACTIVE_MENU: 'ACTIVE_MENU',

  //admin, 13ms45ss
  FETCHING_API: 'FETCHING_API',
  FETCH_GENDER_API_SUCCESSED: 'FETCH_GENDER_API_SUCCESSED',
  FETCH_GENDER_API_FAILED: 'FETCH_GENDER_API_FAILED',
});

export default actionTypes;
